server.port=8080

kafka.brokers=localhost:9092
kafka.consumer.topic=cis.on-demand-read.input
kafka.producer.topic=cis.on-demand-read.output
kafka.group.id=cis-consumer-group

camel.springboot.name=pge-kraken-cis-implementation
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# FTP configuration for polling XML files from the MDM events directory
ftp.host=192.168.4.144
ftp.port=21
ftp.username=PGE_USER
ftp.password=PGE_USER123
ftp.hes.events.remotedir=/readCSVFiles
ftp.pollDelay=60000
