kafka.bootstrap.servers=192.168.4.34:9092
kafka.consumer.group.id=cis-consumer-group
kafka.on-demand-read.input.topic=cis.on-demand-read.input
kafka.device.events.topic=pge.hes.deviceevents.request
kafka.device.events.dlq.topic=pge.hes.deviceevents.dlq
kafka.rcdc.hes.response.topic=pge.hes.connect.disconnect.response
